name: Avaliação

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches:
      - master
      - main

jobs:

  nmecs_defined:
    name: NMEC dos elementos do grupo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "NMEC.txt"
          allow_failure: true

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: grep -E '[0-9]{5}.?-[0-9]{5}.?' NMEC.txt

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Launch servers into background
        run: |
          setup.sh > /dev/null &

      - name: stress test on standby
        run: |
          sleep 5 && stress_test.sh > tests.txt &

      - name: Test with pytest
        timeout-minutes: 2
        run: |
          python3 load_balancer.py -p 8080 -s `cat servers.txt`

      - name: DHT Logs
        uses: actions/upload-artifact@v2
        with:
          name: Stress Tests logs
          path: tests.txt
          retention-days: 1
